version: '3.1'

services :
  web:
    image: alterway/php:5.4-apache
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - 8110:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: postgres:12.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
      POSTGRES_DB: testdb
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 4444:8080